config/routes.rb
Rails.application.routes.draw do
  root to: "static#index"
  devise_for :users, controllers: {sessions: "users/sessions"}
  resources :submissions
  resources :form_elements
  resources :custom_forms do
    resources :submissions
    resources :form_elements
  end
end

app/controllers/custom_forms_controller.rb
class CustomFormsController < ApplicationController
  before_action :set_heading
  before_action :set_custom_form, only: [:show, :edit, :update, :destroy]

  # GET /custom_forms
  # GET /custom_forms.json
  def index
    @custom_forms = CustomForm.all
  end

  # GET /custom_forms/1
  # GET /custom_forms/1.json
  def show
  end

  # GET /custom_forms/new
  def new
    @custom_form = CustomForm.new
  end

  # GET /custom_forms/1/edit
  def edit
  end

  # POST /custom_forms
  # POST /custom_forms.json
  def create
    @custom_form = CustomForm.new(custom_form_params)
    @custom_form.user = current_user
    @custom_form.published_at = Time.zone.now

    respond_to do |format|
      if @custom_form.save
        format.html { redirect_to @custom_form, notice: "Custom form was successfully created." }
        format.json { render :show, status: :created, location: @custom_form }
      else
        format.html { render :new }
        format.json { render json: @custom_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_forms/1
  # PATCH/PUT /custom_forms/1.json
  def update
    respond_to do |format|
      if @custom_form.update(custom_form_params)
        format.html { redirect_to @custom_form, notice: "Custom form was successfully updated." }
        format.json { render :show, status: :ok, location: @custom_form }
      else
        format.html { render :edit }
        format.json { render json: @custom_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_forms/1
  # DELETE /custom_forms/1.json
  def destroy
    @custom_form.destroy
    respond_to do |format|
      format.html { redirect_to custom_forms_url, notice: "Custom form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_custom_form
    @custom_form = CustomForm.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def custom_form_params
    params.require(:custom_form).permit(:name, :user_id, :published_at)
  end

  def set_heading
    @heading = "Custom Forms"
  end
end

app/helpers/custom_forms_helper.rb
module CustomFormsHelper
end

app/views/custom_forms/_form.html.erb
<%= form_with(model: custom_form) do |f| %>
  <% if custom_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(custom_form.errors.count, "error") %> prohibited this Custom Form from being saved:</h2>

      <ul>
        <% custom_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-1">
    <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= f.text_field :name, placeholder:"Enter your form's name", class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md" %>
    </div>
  </div>

  <div class="field mb-1">
    <h1 class="text-2xl">Form Elements</h1>
  </div>
  
  <% f.fields_for :form_elements do |ff| %>
    <%= render :partial => 'form_element', :locals => { :f => ff } %>
  <% end %>
  
  <%= add_child_link "Add an Element", f, :form_elements %>

  <br />

  <div class="actions">
    <%= f.button class: "inline-flex px-4 py-2 text-sm font-medium rounded-md shadow-sm text-white bg-builder-600 hover:bg-builder-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-builder-500" %>
  </div>
<% end %>

app/views/custom_forms/_form_element.html.erb
<div class="fields">
  <p>
    <strong><%= f.label :label, "Enter a label for this element" %></strong><br />
    <%= f.text_field :label %>
  </p>
  <p>
    <strong><%= f.label :tag, "What type of input is this element?" %></strong><br />
    <%= f.select :tag, [["Text box","text_field"], ["Select Menu", "select"], ["Text Area", "text_area"], ["Check Box", "check_box"], ["Date Select", "date_select"]] %>
  </p>
  <p>
    <%= f.check_box :required %>
    <%= f.label :required, "Mark this element as required" %>
  </p>
  <p>
    <strong><%= f.label :values, "Enter the possible values if this is a select menu (one per line)." %></strong><br />
    <%= f.text_area :values, :cols => 50, :rows => 6 %>
  </p>
  <%= remove_child_link "Remove this Element", f %>
  <br /><br />
</div>

app/views/custom_forms/edit.html.erb
<%= render 'form', custom_form: @custom_form %>
<%= link_to 'Show', @custom_form %> |
<%= link_to 'Back', custom_forms_path %>

app/views/custom_forms/index.html.erb
<p id="notice"><%= notice %></p>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Owner
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Published
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Delete</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @custom_forms.each do |custom_form| %>
              <tr>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 hover:text-indigo-300"><%= link_to custom_form.name, custom_form %></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= custom_form.user.email %></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= custom_form.published_at ? custom_form.published_at.strftime("%b %d, %Y") : "--" %></td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%= link_to 'Respond!', new_custom_form_submission_path(custom_form) %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%= link_to 'Edit', edit_custom_form_path(custom_form) %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%= link_to 'Destroy', custom_form, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="text-right">
        <br/>
        <%= link_to 'New Custom Form', new_custom_form_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-builder-600 hover:bg-builder-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-builder-500" %>
      </div>
    </div>
  </div>
</div>

app/views/custom_forms/new.html.erb
<%= render 'form', custom_form: @custom_form %>
<%= link_to 'Back', custom_forms_path %>

app/views/custom_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @custom_form.name %>
</p>

<p>
  <strong>Owned by:</strong>
  <%= @custom_form.user.email %>
</p>

<p>
  <strong>Published:</strong>
  <%= @custom_form.published_at ? @custom_form.published_at.strftime("%b %d, %Y") : "--" %>
</p>

<%= link_to 'Edit', edit_custom_form_path(@custom_form) %> |
<%= link_to 'Back', custom_forms_path %>