config/routes.rb
Rails.application.routes.draw do
  root to: "static#index"
  devise_for :users, controllers: {sessions: "users/sessions"}
  resources :submissions
  resources :form_elements
  resources :custom_forms do
    resources :submissions
    resources :form_elements
  end
end

app/models/form_element.rb
class FormElement < ApplicationRecord
  belongs_to :custom_form
end

app/controllers/form_elements_controller.rb
class FormElementsController < ApplicationController
  before_action :set_form_element, only: [:show, :edit, :update, :destroy]
  before_action :set_heading

  # GET /form_elements
  # GET /form_elements.json
  def index
    @form_elements = FormElement.all
  end

  # GET /form_elements/1
  # GET /form_elements/1.json
  def show
  end

  # GET /form_elements/new
  def new
    @form_element = FormElement.new
  end

  # GET /form_elements/1/edit
  def edit
  end

  # POST /form_elements
  # POST /form_elements.json
  def create
    @form_element = FormElement.new(form_element_params)

    respond_to do |format|
      if @form_element.save
        format.html { redirect_to @form_element, notice: "Form element was successfully created." }
        format.json { render :show, status: :created, location: @form_element }
      else
        format.html { render :new }
        format.json { render json: @form_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_elements/1
  # PATCH/PUT /form_elements/1.json
  def update
    respond_to do |format|
      if @form_element.update(form_element_params)
        format.html { redirect_to @form_element, notice: "Form element was successfully updated." }
        format.json { render :show, status: :ok, location: @form_element }
      else
        format.html { render :edit }
        format.json { render json: @form_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_elements/1
  # DELETE /form_elements/1.json
  def destroy
    @form_element.destroy
    respond_to do |format|
      format.html { redirect_to form_elements_url, notice: "Form element was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_form_element
    @form_element = FormElement.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def form_element_params
    params.require(:form_element).permit(:label, :input_type, :position, :custom_form_id)
  end

  def set_heading
    @heading = "Form Elements"
  end
end

app/helpers/form_elements_helper.rb
module FormElementsHelper
end

app/views/form_elements/_form.html.erb
<%= form_with(model: form_element) do |form| %>
  <% if form_element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form_element.errors.count, "error") %> prohibited this form_element from being saved:</h2>

      <ul>
        <% form_element.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="field">
    <%= form.label :input_type %>
    <%= form.text_field :input_type %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :custom_form_id %>
    <%= form.text_field :custom_form_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/form_elements/edit.html.erb
<h1>Editing Form Element</h1>

<%= render 'form', form_element: @form_element %>

<%= link_to 'Show', @form_element %> |
<%= link_to 'Back', form_elements_path %>

app/views/form_elements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Form Elements</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Input type</th>
      <th>Position</th>
      <th>Custom form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @form_elements.each do |form_element| %>
      <tr>
        <td><%= form_element.label %></td>
        <td><%= form_element.input_type %></td>
        <td><%= form_element.position %></td>
        <td><%= form_element.custom_form_id %></td>
        <td><%= link_to 'Show', form_element %></td>
        <td><%= link_to 'Edit', edit_form_element_path(form_element) %></td>
        <td><%= link_to 'Destroy', form_element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form Element', new_form_element_path %>

app/views/form_elements/new.html.erb
<h1>New Form Element</h1>

<%= render 'form', form_element: @form_element %>

<%= link_to 'Back', form_elements_path %>

app/views/form_elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @form_element.label %>
</p>

<p>
  <strong>Input type:</strong>
  <%= @form_element.input_type %>
</p>

<p>
  <strong>Position:</strong>
  <%= @form_element.position %>
</p>

<p>
  <strong>Custom form:</strong>
  <%= @form_element.custom_form_id %>
</p>

<%= link_to 'Edit', edit_form_element_path(@form_element) %> |
<%= link_to 'Back', form_elements_path %>